### ISSUE TITLE
File picker for Attachments Folder shows only empty side

### ISSUE THREAD

**Issue by stefela** [trinko/contao-zad_sendnews#1]
using zad_sendnews with contao 3.4.0 
the file picker for the attachments folder in the send news manager shows only an empty side. I can't choose a folder. 
If I type the folder-id manually in the databasefield I can send a email and the news headline will appear on the webpage. But then I got the message "This element is using the old Contao 2 SRC-Format ..." So I can see only the Headline but no image or text. (The images are uploaded correct and the subfolders are perfectly created.)

**Comment by trinko** [comment]
I released a new version of zad_sendnews to fix this bug.
You can found it in Contao repository, named as "2.0.1 stable" version.

Please, as I can't do now a real bug test, let me know if the new version solve the problem.

Thanks.

**Comment by stefela** [comment]
I didn't solve the problem. I still have the empty page when i want to select a attachments folder.

**Comment by trinko** [comment]
Ok, I released another version of zad_sendnews: "2.0.2 stable".
I hope it will solve the problem.
Please update zad_sendnews extension and send me a feedback.
Thanks

**Comment by stefela** [comment]
Perfect now I can select a folder. 
But there is still a problem when I attache a picture to the mail (not as "inline picture" - this is working). The upload is working correct. But I still get the message: "Dieses Element verwendet noch das alte Contao 2 SRC-Format. Haben Sie die Datenbank aktualisiert?"
I can "solve" this problem when I do the following steps.
Edit the new news-article zad_sendnews made. In the section "Enclosures" is no file selected. Select the file that was uploaded by using zad_sendnews and save. Then the news is showing correct.

**Comment by trinko** [comment]
Please update zad_sendnews to new release "2.0.3 stable".
I think it will solve the problem.

**Comment by stefela** [comment]
Now I get an fatal error when I try to check for emails using the button in the backend.
Fatal error: Maximum execution time of 30 seconds exceeded in /www/htdocs/.../system/modules/zad_sendnews/classes/ZadSendnewsManager.php on line 942

**Comment by trinko** [comment]
Probably zad_sendnews connected to mail server, but it took too time.
Maybe you have too much email to scan, or maybe the email is too long.
Check the event log, usually you can find more information.

**Comment by stefela** [comment]
I don't know what the problem was. There was only one short email in the mailbox. 
I deleted my "sendnews manager" and made a new one with exact the same settings and now it works. 
Thanks for your help. Everything is working fine now.
